# Generated by Django 4.2.7 on 2023-12-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album_model',
            old_name='musician',
            new_name='musician_relation',
        ),
    ]
